//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 04:58:23 AM EDT 
//


package com.autonomy.vertica.table.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="relationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromTableName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toTableName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromColumnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toColumnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="joinExpression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parentRelationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relation", propOrder = {
    "relationName",
    "fromTableName",
    "toTableName",
    "relationType",
    "fromColumnName",
    "toColumnName",
    "joinExpression",
    "parentRelationName"
})
public class Relation {

    @XmlElement(required = true)
    protected String relationName;
    @XmlElement(required = true)
    protected String fromTableName;
    @XmlElement(required = true)
    protected String toTableName;
    protected String relationType;
    protected String fromColumnName;
    protected String toColumnName;
    protected String joinExpression;
    protected String parentRelationName;

    /**
     * Gets the value of the relationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationName() {
        return relationName;
    }

    /**
     * Sets the value of the relationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationName(String value) {
        this.relationName = value;
    }

    /**
     * Gets the value of the fromTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromTableName() {
        return fromTableName;
    }

    /**
     * Sets the value of the fromTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromTableName(String value) {
        this.fromTableName = value;
    }

    /**
     * Gets the value of the toTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToTableName() {
        return toTableName;
    }

    /**
     * Sets the value of the toTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToTableName(String value) {
        this.toTableName = value;
    }

    /**
     * Gets the value of the relationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * Sets the value of the relationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationType(String value) {
        this.relationType = value;
    }

    /**
     * Gets the value of the fromColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromColumnName() {
        return fromColumnName;
    }

    /**
     * Sets the value of the fromColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromColumnName(String value) {
        this.fromColumnName = value;
    }

    /**
     * Gets the value of the toColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToColumnName() {
        return toColumnName;
    }

    /**
     * Sets the value of the toColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToColumnName(String value) {
        this.toColumnName = value;
    }

    /**
     * Gets the value of the joinExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinExpression() {
        return joinExpression;
    }

    /**
     * Sets the value of the joinExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinExpression(String value) {
        this.joinExpression = value;
    }

	public String getParentRelationName() {
		return parentRelationName;
	}

	public void setParentRelationName(String parentRelationName) {
		this.parentRelationName = parentRelationName;
	}

}
