//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ADMISSION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADMISSION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CONCEPTS" type="{http://schemas.autonomy.com/aci/}CONCEPTS"/>
 *         &lt;element name="DRG" type="{http://schemas.autonomy.com/aci/}DRG"/>
 *         &lt;element name="HADM_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ICD9" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="ICD9_H" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="ICU" type="{http://schemas.autonomy.com/aci/}ICU"/>
 *         &lt;element name="LABEVENTS" type="{http://schemas.autonomy.com/aci/}LABEVENTS"/>
 *         &lt;element name="NOTEEVENT" type="{http://schemas.autonomy.com/aci/}NOTEEVENT" maxOccurs="unbounded"/>
 *         &lt;element name="PATIENT" type="{http://schemas.autonomy.com/aci/}PATIENT"/>
 *         &lt;element name="POEEVENTS" type="{http://schemas.autonomy.com/aci/}POEEVENTS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADMISSION", propOrder = {
    "concepts",
    "drg",
    "hadmid",
    "icd9",
    "icd9H",
    "icu",
    "labevents",
    "noteevent",
    "patient",
    "poeevents"
})
public class ADMISSION {

    @XmlElement(name = "CONCEPTS", required = true)
    protected CONCEPTS concepts;
    @XmlElement(name = "DRG", required = true)
    protected DRG drg;
    @XmlElement(name = "HADM_ID")
    protected int hadmid;
    @XmlElement(name = "ICD9", required = true)
    protected List<String> icd9;
    @XmlElement(name = "ICD9_H", required = true)
    protected List<String> icd9H;
    @XmlElement(name = "ICU", required = true)
    protected ICU icu;
    @XmlElement(name = "LABEVENTS", required = true)
    protected LABEVENTS labevents;
    @XmlElement(name = "NOTEEVENT", required = true)
    protected List<NOTEEVENT> noteevent;
    @XmlElement(name = "PATIENT", required = true)
    protected PATIENT patient;
    @XmlElement(name = "POEEVENTS", required = true)
    protected POEEVENTS poeevents;

    /**
     * Gets the value of the concepts property.
     * 
     * @return
     *     possible object is
     *     {@link CONCEPTS }
     *     
     */
    public CONCEPTS getCONCEPTS() {
        return concepts;
    }

    /**
     * Sets the value of the concepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONCEPTS }
     *     
     */
    public void setCONCEPTS(CONCEPTS value) {
        this.concepts = value;
    }

    /**
     * Gets the value of the drg property.
     * 
     * @return
     *     possible object is
     *     {@link DRG }
     *     
     */
    public DRG getDRG() {
        return drg;
    }

    /**
     * Sets the value of the drg property.
     * 
     * @param value
     *     allowed object is
     *     {@link DRG }
     *     
     */
    public void setDRG(DRG value) {
        this.drg = value;
    }

    /**
     * Gets the value of the hadmid property.
     * 
     */
    public int getHADMID() {
        return hadmid;
    }

    /**
     * Sets the value of the hadmid property.
     * 
     */
    public void setHADMID(int value) {
        this.hadmid = value;
    }

    /**
     * Gets the value of the icd9 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icd9 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getICD9().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getICD9() {
        if (icd9 == null) {
            icd9 = new ArrayList<String>();
        }
        return this.icd9;
    }

    /**
     * Gets the value of the icd9H property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icd9H property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getICD9H().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getICD9H() {
        if (icd9H == null) {
            icd9H = new ArrayList<String>();
        }
        return this.icd9H;
    }

    /**
     * Gets the value of the icu property.
     * 
     * @return
     *     possible object is
     *     {@link ICU }
     *     
     */
    public ICU getICU() {
        return icu;
    }

    /**
     * Sets the value of the icu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICU }
     *     
     */
    public void setICU(ICU value) {
        this.icu = value;
    }

    /**
     * Gets the value of the labevents property.
     * 
     * @return
     *     possible object is
     *     {@link LABEVENTS }
     *     
     */
    public LABEVENTS getLABEVENTS() {
        return labevents;
    }

    /**
     * Sets the value of the labevents property.
     * 
     * @param value
     *     allowed object is
     *     {@link LABEVENTS }
     *     
     */
    public void setLABEVENTS(LABEVENTS value) {
        this.labevents = value;
    }

    /**
     * Gets the value of the noteevent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteevent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNOTEEVENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOTEEVENT }
     * 
     * 
     */
    public List<NOTEEVENT> getNOTEEVENT() {
        if (noteevent == null) {
            noteevent = new ArrayList<NOTEEVENT>();
        }
        return this.noteevent;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link PATIENT }
     *     
     */
    public PATIENT getPATIENT() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PATIENT }
     *     
     */
    public void setPATIENT(PATIENT value) {
        this.patient = value;
    }

    /**
     * Gets the value of the poeevents property.
     * 
     * @return
     *     possible object is
     *     {@link POEEVENTS }
     *     
     */
    public POEEVENTS getPOEEVENTS() {
        return poeevents;
    }

    /**
     * Sets the value of the poeevents property.
     * 
     * @param value
     *     allowed object is
     *     {@link POEEVENTS }
     *     
     */
    public void setPOEEVENTS(POEEVENTS value) {
        this.poeevents = value;
    }

}
