//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOCUMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DREREFERENCE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ADMISSION" type="{http://schemas.autonomy.com/aci/}ADMISSION"/>
 *         &lt;element name="AUTN_IDENTIFIER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AUTN_TASK_BATCH_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DOCTRACKINGID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DREDBNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT", propOrder = {
    "drereference",
    "admission",
    "autnidentifier",
    "autntaskbatchid",
    "doctrackingid",
    "dredbname"
})
@XmlRootElement(name = "document")
public class DOCUMENT {

    @XmlElement(name = "DREREFERENCE")
    protected int drereference;
    @XmlElement(name = "ADMISSION", required = true)
    protected ADMISSION admission;
    @XmlElement(name = "AUTN_IDENTIFIER", required = true)
    protected String autnidentifier;
    @XmlElement(name = "AUTN_TASK_BATCH_ID", required = true)
    protected String autntaskbatchid;
    @XmlElement(name = "DOCTRACKINGID", required = true)
    protected String doctrackingid;
    @XmlElement(name = "DREDBNAME", required = true)
    protected String dredbname;

    /**
     * Gets the value of the drereference property.
     * 
     */
    public int getDREREFERENCE() {
        return drereference;
    }

    /**
     * Sets the value of the drereference property.
     * 
     */
    public void setDREREFERENCE(int value) {
        this.drereference = value;
    }

    /**
     * Gets the value of the admission property.
     * 
     * @return
     *     possible object is
     *     {@link ADMISSION }
     *     
     */
    public ADMISSION getADMISSION() {
        return admission;
    }

    /**
     * Sets the value of the admission property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADMISSION }
     *     
     */
    public void setADMISSION(ADMISSION value) {
        this.admission = value;
    }

    /**
     * Gets the value of the autnidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTNIDENTIFIER() {
        return autnidentifier;
    }

    /**
     * Sets the value of the autnidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTNIDENTIFIER(String value) {
        this.autnidentifier = value;
    }

    /**
     * Gets the value of the autntaskbatchid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTNTASKBATCHID() {
        return autntaskbatchid;
    }

    /**
     * Sets the value of the autntaskbatchid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTNTASKBATCHID(String value) {
        this.autntaskbatchid = value;
    }

    /**
     * Gets the value of the doctrackingid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCTRACKINGID() {
        return doctrackingid;
    }

    /**
     * Sets the value of the doctrackingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCTRACKINGID(String value) {
        this.doctrackingid = value;
    }

    /**
     * Gets the value of the dredbname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDREDBNAME() {
        return dredbname;
    }

    /**
     * Sets the value of the dredbname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDREDBNAME(String value) {
        this.dredbname = value;
    }

}
