//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DRG complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DRG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="COST_WEIGHT" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="COST_WEIGHT_GRP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DISPLAY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ITEMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DRG", propOrder = {
    "code",
    "costweight",
    "costweightgrp",
    "desc",
    "display",
    "itemid"
})
public class DRG {

    @XmlElement(name = "CODE")
    protected int code;
    @XmlElement(name = "COST_WEIGHT")
    protected double costweight;
    @XmlElement(name = "COST_WEIGHT_GRP", required = true)
    protected String costweightgrp;
    @XmlElement(name = "DESC", required = true)
    protected String desc;
    @XmlElement(name = "DISPLAY", required = true)
    protected String display;
    @XmlElement(name = "ITEMID")
    protected int itemid;

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCODE() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCODE(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the costweight property.
     * 
     */
    public double getCOSTWEIGHT() {
        return costweight;
    }

    /**
     * Sets the value of the costweight property.
     * 
     */
    public void setCOSTWEIGHT(double value) {
        this.costweight = value;
    }

    /**
     * Gets the value of the costweightgrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSTWEIGHTGRP() {
        return costweightgrp;
    }

    /**
     * Sets the value of the costweightgrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSTWEIGHTGRP(String value) {
        this.costweightgrp = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISPLAY() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISPLAY(String value) {
        this.display = value;
    }

    /**
     * Gets the value of the itemid property.
     * 
     */
    public int getITEMID() {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     */
    public void setITEMID(int value) {
        this.itemid = value;
    }

}
