//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EVENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EVENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NAME_H" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OCCURRENCES" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EVENT", propOrder = {
    "name",
    "nameh",
    "occurrences"
})
public class EVENT {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "NAME_H", required = true)
    protected String nameh;
    @XmlElement(name = "OCCURRENCES")
    protected int occurrences;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAMEH() {
        return nameh;
    }

    /**
     * Sets the value of the nameh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAMEH(String value) {
        this.nameh = value;
    }

    /**
     * Gets the value of the occurrences property.
     * 
     */
    public int getOCCURRENCES() {
        return occurrences;
    }

    /**
     * Sets the value of the occurrences property.
     * 
     */
    public void setOCCURRENCES(int value) {
        this.occurrences = value;
    }

}
