//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ICUDETAILS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ICUDETAILS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FIRST_CAREUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ICUSTAY_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="INTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LAST_CAREUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LOS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LOS_GRP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MEDEVENTS" type="{http://schemas.autonomy.com/aci/}MEDEVENTS"/>
 *         &lt;element name="OUTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ICUDETAILS", propOrder = {
    "firstcareunit",
    "icustayid",
    "intime",
    "lastcareunit",
    "los",
    "losgrp",
    "medevents",
    "outtime"
})
public class ICUDETAILS {

    @XmlElement(name = "FIRST_CAREUNIT", required = true)
    protected String firstcareunit;
    @XmlElement(name = "ICUSTAY_ID")
    protected int icustayid;
    @XmlElement(name = "INTIME", required = true)
    protected String intime;
    @XmlElement(name = "LAST_CAREUNIT", required = true)
    protected String lastcareunit;
    @XmlElement(name = "LOS")
    protected int los;
    @XmlElement(name = "LOS_GRP", required = true)
    protected String losgrp;
    @XmlElement(name = "MEDEVENTS", required = true)
    protected MEDEVENTS medevents;
    @XmlElement(name = "OUTTIME", required = true)
    protected String outtime;

    /**
     * Gets the value of the firstcareunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTCAREUNIT() {
        return firstcareunit;
    }

    /**
     * Sets the value of the firstcareunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTCAREUNIT(String value) {
        this.firstcareunit = value;
    }

    /**
     * Gets the value of the icustayid property.
     * 
     */
    public int getICUSTAYID() {
        return icustayid;
    }

    /**
     * Sets the value of the icustayid property.
     * 
     */
    public void setICUSTAYID(int value) {
        this.icustayid = value;
    }

    /**
     * Gets the value of the intime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTIME() {
        return intime;
    }

    /**
     * Sets the value of the intime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTIME(String value) {
        this.intime = value;
    }

    /**
     * Gets the value of the lastcareunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTCAREUNIT() {
        return lastcareunit;
    }

    /**
     * Sets the value of the lastcareunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTCAREUNIT(String value) {
        this.lastcareunit = value;
    }

    /**
     * Gets the value of the los property.
     * 
     */
    public int getLOS() {
        return los;
    }

    /**
     * Sets the value of the los property.
     * 
     */
    public void setLOS(int value) {
        this.los = value;
    }

    /**
     * Gets the value of the losgrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOSGRP() {
        return losgrp;
    }

    /**
     * Sets the value of the losgrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOSGRP(String value) {
        this.losgrp = value;
    }

    /**
     * Gets the value of the medevents property.
     * 
     * @return
     *     possible object is
     *     {@link MEDEVENTS }
     *     
     */
    public MEDEVENTS getMEDEVENTS() {
        return medevents;
    }

    /**
     * Sets the value of the medevents property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEDEVENTS }
     *     
     */
    public void setMEDEVENTS(MEDEVENTS value) {
        this.medevents = value;
    }

    /**
     * Gets the value of the outtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOUTTIME() {
        return outtime;
    }

    /**
     * Sets the value of the outtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOUTTIME(String value) {
        this.outtime = value;
    }

}
