//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NOTEEVENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NOTEEVENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CAREGIVER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CAREUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TEXT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TEXT_H" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TITLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NOTEEVENT", propOrder = {
    "caregiver",
    "careunit",
    "category",
    "text",
    "texth",
    "title"
})
public class NOTEEVENT {

    @XmlElement(name = "CAREGIVER", required = true)
    protected String caregiver;
    @XmlElement(name = "CAREUNIT", required = true)
    protected String careunit;
    @XmlElement(name = "CATEGORY", required = true)
    protected String category;
    @XmlElement(name = "TEXT", required = true)
    protected String text;
    @XmlElement(name = "TEXT_H", required = true)
    protected String texth;
    @XmlElement(name = "TITLE", required = true)
    protected String title;

    /**
     * Gets the value of the caregiver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAREGIVER() {
        return caregiver;
    }

    /**
     * Sets the value of the caregiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAREGIVER(String value) {
        this.caregiver = value;
    }

    /**
     * Gets the value of the careunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAREUNIT() {
        return careunit;
    }

    /**
     * Sets the value of the careunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAREUNIT(String value) {
        this.careunit = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCATEGORY() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCATEGORY(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the texth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTH() {
        return texth;
    }

    /**
     * Sets the value of the texth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTH(String value) {
        this.texth = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

}
