//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.autonomy.vertica.docview package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.autonomy.vertica.docview
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Autnresponse }
     * 
     */
    public Autnresponse createAutnresponse() {
        return new Autnresponse();
    }

    /**
     * Create an instance of {@link Responsedata }
     * 
     */
    public Responsedata createResponsedata() {
        return new Responsedata();
    }

    /**
     * Create an instance of {@link PATIENT }
     * 
     */
    public PATIENT createPATIENT() {
        return new PATIENT();
    }

    /**
     * Create an instance of {@link ICUDETAILS }
     * 
     */
    public ICUDETAILS createICUDETAILS() {
        return new ICUDETAILS();
    }

    /**
     * Create an instance of {@link SMISA }
     * 
     */
    public SMISA createSMISA() {
        return new SMISA();
    }

    /**
     * Create an instance of {@link DOCUMENT }
     * 
     */
    public DOCUMENT createDOCUMENT() {
        return new DOCUMENT();
    }

    /**
     * Create an instance of {@link POEEVENTS }
     * 
     */
    public POEEVENTS createPOEEVENTS() {
        return new POEEVENTS();
    }

    /**
     * Create an instance of {@link SM }
     * 
     */
    public SM createSM() {
        return new SM();
    }

    /**
     * Create an instance of {@link CONCEPTS }
     * 
     */
    public CONCEPTS createCONCEPTS() {
        return new CONCEPTS();
    }

    /**
     * Create an instance of {@link DRG }
     * 
     */
    public DRG createDRG() {
        return new DRG();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Hit }
     * 
     */
    public Hit createHit() {
        return new Hit();
    }

    /**
     * Create an instance of {@link NOTEEVENT }
     * 
     */
    public NOTEEVENT createNOTEEVENT() {
        return new NOTEEVENT();
    }

    /**
     * Create an instance of {@link ICU }
     * 
     */
    public ICU createICU() {
        return new ICU();
    }

    /**
     * Create an instance of {@link EVENT }
     * 
     */
    public EVENT createEVENT() {
        return new EVENT();
    }

    /**
     * Create an instance of {@link LABEVENTS }
     * 
     */
    public LABEVENTS createLABEVENTS() {
        return new LABEVENTS();
    }

    /**
     * Create an instance of {@link MEDEVENTS }
     * 
     */
    public MEDEVENTS createMEDEVENTS() {
        return new MEDEVENTS();
    }

    /**
     * Create an instance of {@link ADMISSION }
     * 
     */
    public ADMISSION createADMISSION() {
        return new ADMISSION();
    }

}
