//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.autonomy.com/aci/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.autonomy.vertica.docview;
