//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 07:04:07 AM EDT 
//


package com.autonomy.vertica.docview;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PATIENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PATIENT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ADMISSION_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADMISSION_DATE_DAYMON_GRP" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ADMISSION_DATE_DAYWEEK_GRP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADMISSION_DATE_MON_GRP" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ADMISSION_DATE_WEEK_GRP" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ADMISSION_DATE_YRMON" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADMISSION_SOURCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADMISSION_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AGE_AT_ADMISSION" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AGE_AT_ADMISSION_GRP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AGE_AT_DEATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AGE_AT_DEATH_GRP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DISCHARGE_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ETHNICITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HOSPITAL_EXPIRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MARITAL_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OVERALL_PAYOR_GROUP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RELIGION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SEX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBJECT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PATIENT", propOrder = {
    "admissiondate",
    "admissiondatedaymongrp",
    "admissiondatedayweekgrp",
    "admissiondatemongrp",
    "admissiondateweekgrp",
    "admissiondateyrmon",
    "admissionsource",
    "admissiontype",
    "ageatadmission",
    "ageatadmissiongrp",
    "ageatdeath",
    "ageatdeathgrp",
    "dischargedate",
    "dob",
    "dod",
    "ethnicity",
    "hospitalexpire",
    "maritalstatus",
    "overallpayorgroup",
    "religion",
    "sex",
    "subjectid"
})
public class PATIENT {

    @XmlElement(name = "ADMISSION_DATE", required = true)
    protected String admissiondate;
    @XmlElement(name = "ADMISSION_DATE_DAYMON_GRP")
    protected int admissiondatedaymongrp;
    @XmlElement(name = "ADMISSION_DATE_DAYWEEK_GRP", required = true)
    protected String admissiondatedayweekgrp;
    @XmlElement(name = "ADMISSION_DATE_MON_GRP")
    protected int admissiondatemongrp;
    @XmlElement(name = "ADMISSION_DATE_WEEK_GRP")
    protected int admissiondateweekgrp;
    @XmlElement(name = "ADMISSION_DATE_YRMON", required = true)
    protected String admissiondateyrmon;
    @XmlElement(name = "ADMISSION_SOURCE", required = true)
    protected String admissionsource;
    @XmlElement(name = "ADMISSION_TYPE", required = true)
    protected String admissiontype;
    @XmlElement(name = "AGE_AT_ADMISSION")
    protected int ageatadmission;
    @XmlElement(name = "AGE_AT_ADMISSION_GRP", required = true)
    protected String ageatadmissiongrp;
    @XmlElement(name = "AGE_AT_DEATH", required = true)
    protected String ageatdeath;
    @XmlElement(name = "AGE_AT_DEATH_GRP", required = true)
    protected String ageatdeathgrp;
    @XmlElement(name = "DISCHARGE_DATE", required = true)
    protected String dischargedate;
    @XmlElement(name = "DOB", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dob;
    @XmlElement(name = "DOD", required = true)
    protected String dod;
    @XmlElement(name = "ETHNICITY", required = true)
    protected String ethnicity;
    @XmlElement(name = "HOSPITAL_EXPIRE", required = true)
    protected String hospitalexpire;
    @XmlElement(name = "MARITAL_STATUS", required = true)
    protected String maritalstatus;
    @XmlElement(name = "OVERALL_PAYOR_GROUP", required = true)
    protected String overallpayorgroup;
    @XmlElement(name = "RELIGION", required = true)
    protected String religion;
    @XmlElement(name = "SEX", required = true)
    protected String sex;
    @XmlElement(name = "SUBJECT_ID")
    protected int subjectid;

    /**
     * Gets the value of the admissiondate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMISSIONDATE() {
        return admissiondate;
    }

    /**
     * Sets the value of the admissiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMISSIONDATE(String value) {
        this.admissiondate = value;
    }

    /**
     * Gets the value of the admissiondatedaymongrp property.
     * 
     */
    public int getADMISSIONDATEDAYMONGRP() {
        return admissiondatedaymongrp;
    }

    /**
     * Sets the value of the admissiondatedaymongrp property.
     * 
     */
    public void setADMISSIONDATEDAYMONGRP(int value) {
        this.admissiondatedaymongrp = value;
    }

    /**
     * Gets the value of the admissiondatedayweekgrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMISSIONDATEDAYWEEKGRP() {
        return admissiondatedayweekgrp;
    }

    /**
     * Sets the value of the admissiondatedayweekgrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMISSIONDATEDAYWEEKGRP(String value) {
        this.admissiondatedayweekgrp = value;
    }

    /**
     * Gets the value of the admissiondatemongrp property.
     * 
     */
    public int getADMISSIONDATEMONGRP() {
        return admissiondatemongrp;
    }

    /**
     * Sets the value of the admissiondatemongrp property.
     * 
     */
    public void setADMISSIONDATEMONGRP(int value) {
        this.admissiondatemongrp = value;
    }

    /**
     * Gets the value of the admissiondateweekgrp property.
     * 
     */
    public int getADMISSIONDATEWEEKGRP() {
        return admissiondateweekgrp;
    }

    /**
     * Sets the value of the admissiondateweekgrp property.
     * 
     */
    public void setADMISSIONDATEWEEKGRP(int value) {
        this.admissiondateweekgrp = value;
    }

    /**
     * Gets the value of the admissiondateyrmon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMISSIONDATEYRMON() {
        return admissiondateyrmon;
    }

    /**
     * Sets the value of the admissiondateyrmon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMISSIONDATEYRMON(String value) {
        this.admissiondateyrmon = value;
    }

    /**
     * Gets the value of the admissionsource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMISSIONSOURCE() {
        return admissionsource;
    }

    /**
     * Sets the value of the admissionsource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMISSIONSOURCE(String value) {
        this.admissionsource = value;
    }

    /**
     * Gets the value of the admissiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMISSIONTYPE() {
        return admissiontype;
    }

    /**
     * Sets the value of the admissiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMISSIONTYPE(String value) {
        this.admissiontype = value;
    }

    /**
     * Gets the value of the ageatadmission property.
     * 
     */
    public int getAGEATADMISSION() {
        return ageatadmission;
    }

    /**
     * Sets the value of the ageatadmission property.
     * 
     */
    public void setAGEATADMISSION(int value) {
        this.ageatadmission = value;
    }

    /**
     * Gets the value of the ageatadmissiongrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGEATADMISSIONGRP() {
        return ageatadmissiongrp;
    }

    /**
     * Sets the value of the ageatadmissiongrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGEATADMISSIONGRP(String value) {
        this.ageatadmissiongrp = value;
    }

    /**
     * Gets the value of the ageatdeath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGEATDEATH() {
        return ageatdeath;
    }

    /**
     * Sets the value of the ageatdeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGEATDEATH(String value) {
        this.ageatdeath = value;
    }

    /**
     * Gets the value of the ageatdeathgrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGEATDEATHGRP() {
        return ageatdeathgrp;
    }

    /**
     * Sets the value of the ageatdeathgrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGEATDEATHGRP(String value) {
        this.ageatdeathgrp = value;
    }

    /**
     * Gets the value of the dischargedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISCHARGEDATE() {
        return dischargedate;
    }

    /**
     * Sets the value of the dischargedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISCHARGEDATE(String value) {
        this.dischargedate = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDOB(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the dod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOD() {
        return dod;
    }

    /**
     * Sets the value of the dod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOD(String value) {
        this.dod = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETHNICITY() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETHNICITY(String value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the hospitalexpire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOSPITALEXPIRE() {
        return hospitalexpire;
    }

    /**
     * Sets the value of the hospitalexpire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOSPITALEXPIRE(String value) {
        this.hospitalexpire = value;
    }

    /**
     * Gets the value of the maritalstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARITALSTATUS() {
        return maritalstatus;
    }

    /**
     * Sets the value of the maritalstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARITALSTATUS(String value) {
        this.maritalstatus = value;
    }

    /**
     * Gets the value of the overallpayorgroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOVERALLPAYORGROUP() {
        return overallpayorgroup;
    }

    /**
     * Sets the value of the overallpayorgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOVERALLPAYORGROUP(String value) {
        this.overallpayorgroup = value;
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELIGION() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELIGION(String value) {
        this.religion = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEX() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEX(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the subjectid property.
     * 
     */
    public int getSUBJECTID() {
        return subjectid;
    }

    /**
     * Sets the value of the subjectid property.
     * 
     */
    public void setSUBJECTID(int value) {
        this.subjectid = value;
    }

}
