//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.19 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customFilterSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customFilterSection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence> *         
 *         &lt;element name="mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="defaultType" type="{http://www.w3.org/2001/XMLSchema}String" minOccurs="0"/>          
 *         &lt;element name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}String" minOccurs="0"/>
 *         &lt;element name="filters" type="{http://www.autonomy.com/find/fields}customFiltersGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customFilterSection", propOrder = {
    "mandatory",
    "hidden",
    "defaultType",
    "defaultValue",
    "filters"
    
})
public class CustomFilterSection {
	
	@XmlElement(defaultValue = "false")
    protected Boolean mandatory = Boolean.FALSE;   
    @XmlElement(defaultValue = "false")
    protected Boolean hidden = Boolean.FALSE;
    @XmlElement(defaultValue = "date")
    protected String defaultType = "DATE";
    @XmlElement(defaultValue = "sysdate")
    protected String defaultValue = "SYSDATE";
    protected CustomFiltersGroup filters;
    
	public Boolean isMandatory() {
		return mandatory;
	}
	public void setMandatory(Boolean mandatory) {
		this.mandatory = mandatory;
	}
	public Boolean isHidden() {
		return hidden;
	}
	public void setHidden(Boolean hidden) {
		this.hidden = hidden;
	}
	public String getDefaultType() {
		return defaultType;
	}
	public void setDefaultType(String defaultType) {
		this.defaultType = defaultType;
	}
	public String getDefaultValue() {
		return defaultValue;
	}
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}
	public CustomFiltersGroup getFilters() {
		return filters;
	}
	public void setFilters(CustomFiltersGroup filters) {
		this.filters = filters;
	}

}