//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.19 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customFilterObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customFilterObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence> *         
 *         &lt;element name="relationName" type="{http://www.w3.org/2001/XMLSchema}String" minOccurs="0"/>          
 *         &lt;element name="customFilterExpression" type="{http://www.w3.org/2001/XMLSchema}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customFilterObject", propOrder = {
    "relationName",
    "customFilterExpression"		
})
public class CustomFilterObject {
	
    protected String relationName;    
    protected String customFilterExpression;
    
	public String getRelationName() {
		return relationName;
	}
	public void setRelationName(String relationName) {
		this.relationName = relationName;
	}
	public String getCustomFilterExpression() {
		return customFilterExpression;
	}
	public void setCustomFilterExpression(String customFilterExpression) {
		this.customFilterExpression = customFilterExpression;
	}

}