//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.19 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customFiltersGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customFiltersGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence> *         
 *         
 *         &lt;element name="customFilter" type="{http://www.autonomy.com/find/fields}customFilterObject" minOccurs="0" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customFiltersGroup", propOrder = {
    "customFilter"
})
public class CustomFiltersGroup {
	
	

	@XmlElement(required = true)
	 protected List<CustomFilterObject> customFilter;
	
	 public List<CustomFilterObject> getCustomFilter() {
		 if (customFilter == null) {
			 customFilter = new ArrayList<CustomFilterObject>();
	     }
		 return this.customFilter;
	 }

}