//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filterField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filterField">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="printable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="aggregated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="filterDefaultSelect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="topicmapDefaultSelect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="referenceType" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="popType" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="popDefaultSelect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="indexed" type="{http://www.autonomy.com/find/fields}idolField" minOccurs="0"/>
 *             &lt;element name="parametric" type="{http://www.autonomy.com/find/fields}paraField" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="custom" type="{http://www.autonomy.com/find/fields}customField"/>
 *         &lt;/choice>
 *         &lt;element name="vertica" type="{http://www.autonomy.com/find/fields}verticaField" minOccurs="0"/>
 *         &lt;element name="restricted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="fieldOrdinal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterField", propOrder = {
    "name",
    "displayName",
    "printable",
    "weight",
    "aggregated",
    "filterDefaultSelect",
    "topicmapDefaultSelect",
    "referenceType",
    "popType",
    "popDefaultSelect",
    "indexed",
    "parametric",
    "custom",
    "vertica",
    "restricted",
    "fieldOrdinal"
    
})
public class FilterField {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String displayName;
    @XmlElement(defaultValue = "true")
    protected Boolean printable = Boolean.TRUE;
    @XmlElement(defaultValue = "0")
    protected Integer weight = 0;
    @XmlElement(defaultValue = "false")
    protected Boolean aggregated = Boolean.FALSE;
    @XmlElement(defaultValue = "false")
    protected Boolean filterDefaultSelect = Boolean.FALSE;
    @XmlElement(defaultValue = "true")
    protected Boolean topicmapDefaultSelect = Boolean.FALSE;
    @XmlElement(defaultValue = "false")
    protected Boolean referenceType = Boolean.FALSE;
    @XmlElement(defaultValue = "false")
    protected Boolean popType = Boolean.FALSE;
    @XmlElement(defaultValue = "false")
    protected Boolean popDefaultSelect = Boolean.FALSE;
    protected IdolField indexed;
    protected ParaField parametric;
    protected CustomField custom;
    protected VerticaField vertica;
    @XmlElement(defaultValue = "false")
    protected Boolean restricted = Boolean.FALSE;
    @XmlElement(defaultValue = "0")
    protected Integer fieldOrdinal = 0;

    public GroupMeta getParentCategory() {
        return parentCategory;
    }

    public void setParentCategory(GroupMeta parentCategory) {
        this.parentCategory = parentCategory;
    }

    public GroupMeta getParentGroup() {
        return parentGroup;
    }

    public void setParentGroup(GroupMeta parentGroup) {
        this.parentGroup = parentGroup;
    }

    @XmlTransient
    protected GroupMeta parentCategory;
    @XmlTransient
    protected GroupMeta parentGroup;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the printable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrintable() {
        return printable;
    }

    /**
     * Sets the value of the printable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrintable(Boolean value) {
        this.printable = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeight(Integer value) {
        this.weight = value;
    }

    /**
     * Gets the value of the aggregated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAggregated() {
        return aggregated;
    }

    /**
     * Sets the value of the aggregated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAggregated(Boolean value) {
        this.aggregated = value;
    }

    /**
     * Gets the value of the filterDefaultSelect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFilterDefaultSelect() {
        return filterDefaultSelect;
    }

    /**
     * Sets the value of the filterDefaultSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterDefaultSelect(Boolean value) {
        this.filterDefaultSelect = value;
    }

    /**
     * Gets the value of the topicmapDefaultSelect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTopicmapDefaultSelect() {
        return topicmapDefaultSelect;
    }

    /**
     * Sets the value of the topicmapDefaultSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTopicmapDefaultSelect(Boolean value) {
        this.topicmapDefaultSelect = value;
    }

    /**
     * Gets the value of the referenceType property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReferenceType() {
        return referenceType;
    }

    /**
     * Sets the value of the referenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferenceType(Boolean value) {
        this.referenceType = value;
    }

    /**
     * Gets the value of the popType property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPopType() {
        return popType;
    }

    /**
     * Sets the value of the popType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPopType(Boolean value) {
        this.popType = value;
    }

    /**
     * Gets the value of the popDefaultSelect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPopDefaultSelect() {
        return popDefaultSelect;
    }

    /**
     * Sets the value of the popDefaultSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPopDefaultSelect(Boolean value) {
        this.popDefaultSelect = value;
    }

    /**
     * Gets the value of the indexed property.
     * 
     * @return
     *     possible object is
     *     {@link IdolField }
     *     
     */
    public IdolField getIndexed() {
        return indexed;
    }

    /**
     * Sets the value of the indexed property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdolField }
     *     
     */
    public void setIndexed(IdolField value) {
        this.indexed = value;
    }

    /**
     * Gets the value of the parametric property.
     * 
     * @return
     *     possible object is
     *     {@link ParaField }
     *     
     */
    public ParaField getParametric() {
        return parametric;
    }

    /**
     * Sets the value of the parametric property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParaField }
     *     
     */
    public void setParametric(ParaField value) {
        this.parametric = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link CustomField }
     *     
     */
    public CustomField getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomField }
     *     
     */
    public void setCustom(CustomField value) {
        this.custom = value;
    }

    /**
     * Gets the value of the vertica property.
     * 
     * @return
     *     possible object is
     *     {@link VerticaField }
     *     
     */
    public VerticaField getVertica() {
        return vertica;
    }

    /**
     * Sets the value of the vertica property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticaField }
     *     
     */
    public void setVertica(VerticaField value) {
        this.vertica = value;
    }

	public Boolean isRestricted() {
		return restricted;
	}

	public void setRestricted(Boolean restricted) {
		this.restricted = restricted;
	}

	public Integer getFieldOrdinal() {
		return fieldOrdinal;
	}

	public void setFieldOrdinal(Integer fieldOrdinal) {
		this.fieldOrdinal = fieldOrdinal;
	}

}
