//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filtersCategory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filtersCategory">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.autonomy.com/find/fields}groupMeta">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="group" type="{http://www.autonomy.com/find/fields}filtersGroup"/>
 *         &lt;element name="filterField" type="{http://www.autonomy.com/find/fields}filterField"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filtersCategory", propOrder = {
    "groupOrFilterField"
})
public class FiltersCategory
    extends GroupMeta
{

    @XmlElements({
        @XmlElement(name = "group", type = FiltersGroup.class),
        @XmlElement(name = "filterField", type = FilterField.class)
    })
    protected List<Object> groupOrFilterField;

    /**
     * Gets the value of the groupOrFilterField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupOrFilterField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupOrFilterField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FiltersGroup }
     * {@link FilterField }
     * 
     * 
     */
    public List<Object> getGroupOrFilterField() {
        if (groupOrFilterField == null) {
            groupOrFilterField = new ArrayList<Object>();
        }
        return this.groupOrFilterField;
    }

}
