//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.autonomy.find.fields package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.autonomy.find.fields
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FilterFields }
     * 
     */
    public FilterFields createFilterFields() {
        return new FilterFields();
    }

    /**
     * Create an instance of {@link FiltersCategory }
     * 
     */
    public FiltersCategory createFiltersCategory() {
        return new FiltersCategory();
    }

    /**
     * Create an instance of {@link SelectOperator }
     * 
     */
    public SelectOperator createSelectOperator() {
        return new SelectOperator();
    }

    /**
     * Create an instance of {@link CustomField }
     * 
     */
    public CustomField createCustomField() {
        return new CustomField();
    }

    /**
     * Create an instance of {@link IdolField }
     * 
     */
    public IdolField createIdolField() {
        return new IdolField();
    }

    /**
     * Create an instance of {@link ParaField }
     * 
     */
    public ParaField createParaField() {
        return new ParaField();
    }

    /**
     * Create an instance of {@link FiltersGroup }
     * 
     */
    public FiltersGroup createFiltersGroup() {
        return new FiltersGroup();
    }

    /**
     * Create an instance of {@link GroupMeta }
     * 
     */
    public GroupMeta createGroupMeta() {
        return new GroupMeta();
    }

    /**
     * Create an instance of {@link FilterField }
     * 
     */
    public FilterField createFilterField() {
        return new FilterField();
    }

    /**
     * Create an instance of {@link TableSection }
     * 
     */
    public TableSection createTableSection() {
        return new TableSection();
    }

    /**
     * Create an instance of {@link SelectSection }
     * 
     */
    public SelectSection createSelectSection() {
        return new SelectSection();
    }

    /**
     * Create an instance of {@link VerticaField }
     * 
     */
    public VerticaField createVerticaField() {
        return new VerticaField();
    }

}
