//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectOperator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selectOperator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aggregateOperator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="miscOperator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="selectExpression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/> *         
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectOperator", propOrder = {
    "aggregateOperator",
    "miscOperator",
    "selectExpression"
})
public class SelectOperator {

    protected String aggregateOperator;
    protected String miscOperator;
    protected String selectExpression;

    public String getSelectExpression() {
		return selectExpression;
	}

	public void setSelectExpression(String selectExpression) {
		this.selectExpression = selectExpression;
	}

	/**
     * Gets the value of the aggregateOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregateOperator() {
        return aggregateOperator;
    }

    /**
     * Sets the value of the aggregateOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregateOperator(String value) {
        this.aggregateOperator = value;
    }

    /**
     * Gets the value of the dateOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscOperator() {
        return miscOperator;
    }

    /**
     * Sets the value of the dateOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscOperator(String value) {
        this.miscOperator = value;
    }

}
