//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tableSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tableSection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromTable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dimensionTable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mappingKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tableRelationKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tableSection", propOrder = {
    "fromTable",
    "dimensionTable",
    "mappingKey",
    "tableRelationKey"
})
public class TableSection {

    protected String fromTable;
    protected String dimensionTable;
    protected String mappingKey;
    protected String tableRelationKey;

    /**
     * Gets the value of the fromTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromTable() {
        return fromTable;
    }

    /**
     * Sets the value of the fromTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromTable(String value) {
        this.fromTable = value;
    }

    /**
     * Gets the value of the dimensionTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimensionTable() {
        return dimensionTable;
    }

    /**
     * Sets the value of the dimensionTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimensionTable(String value) {
        this.dimensionTable = value;
    }

	public String getMappingKey() {
		return mappingKey;
	}

	public void setMappingKey(String mappingKey) {
		this.mappingKey = mappingKey;
	}

	public String getTableRelationKey() {
		return tableRelationKey;
	}

	public void setTableRelationKey(String tableRelationKey) {
		this.tableRelationKey = tableRelationKey;
	}

}
