//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:33:42 AM EDT 
//


package com.autonomy.find.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verticaField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="verticaField">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="schema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="table" type="{http://www.autonomy.com/find/fields}tableSection" minOccurs="0"/>
 *         &lt;element name="column" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resultView" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="overrideSection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="select" type="{http://www.autonomy.com/find/fields}selectSection" minOccurs="0"/>
 *         &lt;element name="filterSection" type="{http://www.autonomy.com/find/fields}customFilterSection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "verticaField", propOrder = {
    "schema",
    "table",
    "column",
    "dataType",
    "resultView",
    "overrideSection",
    "select",
    "filterSection"
})
public class VerticaField {

    protected String schema;
    protected TableSection table;
    protected String column;
    @XmlElement(defaultValue = "text")
    protected String dataType = "TEXT";
    protected String resultView;
    protected OverrideSection overrideSection;
    protected SelectSection select;
    //protected String customFilter;
    protected CustomFilterSection filterSection;

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link TableSection }
     *     
     */
    public TableSection getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableSection }
     *     
     */
    public void setTable(TableSection value) {
        this.table = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the resultView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultView() {
        return resultView;
    }

    /**
     * Sets the value of the resultView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultView(String value) {
        this.resultView = value;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link SelectSection }
     *     
     */
    public SelectSection getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectSection }
     *     
     */
    public void setSelect(SelectSection value) {
        this.select = value;
    }

	/**
	 * @return
	 */
	public CustomFilterSection getFilterSection() {
		return filterSection;
	}

	/**
	 * @param filterSection
	 */
	public void setFilterSection(CustomFilterSection filterSection) {
		this.filterSection = filterSection;
	}

	public OverrideSection getOverrideSection() {
		return overrideSection;
	}

	public void setOverrideSection(OverrideSection overrideSection) {
		this.overrideSection = overrideSection;
	}


    


}
